services:
  db-account:
    image: postgres:18
    container_name: pitamai-account-postgres
    restart: always
    environment:
      POSTGRES_USER: maimai
      POSTGRES_PASSWORD: maimai
      POSTGRES_DB: maimai_dev_account
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maimai -d maimai_dev_account"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    name: pitamai-account-pgdata
