services:
  db-account:
    image: postgres:18
    container_name: pitamai-account-postgres
    environment:
      POSTGRES_USER: maimai
      POSTGRES_PASSWORD: maimai
      POSTGRES_DB: maimai_dev_account
    ports:
      - '5432:5432'
    volumes:
      - pitamai-account-pgdata:/var/lib/postgresql/data

volumes:
  pitamai-account-pgdata:
