allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  unrs-resolver: true
  vue-demi: true
  '@parcel/watcher': true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - better-sqlite3
  - esbuild
  - prisma
  - unrs-resolver
  - vue-demi
